### PR TITLE
Add a dependency to pom file to fix compilation

### PR DESCRIPTION
**Pull request by anwar6953**
Add a dependency to pom file to fix compilation. I included an exclusion to the dependency, as was done in https://github.com/data-integrations/dynamic-partitioner/pull/1.

Compilation was broken in https://github.com/data-integrations/google-cloud/pull/64 (I'm not sure how the changes in that PR was compiling), but without this change, I get:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/RecordFilterOutputFormat.java:[34,32] package org.apache.orc.mapreduce does not exist
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/StructuredToOrcTransformer.java:[33,22] package org.apache.orc does not exist
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/StructuredToOrcTransformer.java:[34,29] package org.apache.orc.mapred does not exist
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/StructuredToOrcTransformer.java:[47,83] cannot find symbol
  symbol: class OrcStruct
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/StructuredToOrcTransformer.java:[50,29] cannot find symbol
  symbol:   class TypeDescription
  location: class co.cask.gcp.common.StructuredToOrcTransformer
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/StructuredToOrcTransformer.java:[53,10] cannot find symbol
  symbol:   class OrcStruct
  location: class co.cask.gcp.common.StructuredToOrcTransformer
[ERROR] /Users/alianwar/src/google-cloud/src/main/java/co/cask/gcp/common/StructuredToOrcTransformer.java:[70,11] cannot find symbol
  symbol:   class OrcStruct
  location: class co.cask.gcp.common.StructuredToOrcTransformer
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:11 min
[INFO] Finished at: 2018-11-08T14:09:12-08:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by anwar6953** [comment]
Compilation now passes:
image
